[project]
name = "graph-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.124.0",
    "pydantic>=2.12.5",
    "sumy>=0.11.0",
]
